version: '3.8'

services:
  db: 
    image: postgres:15-alpine
    environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: password123
       POSTGRES_DB: cineTrack-project
    ports:
      - "5000:5432"
    volumes:
      - pg_data_v2:/var/lib/postgresql/data 
      # the volumes for not removal of data when the pc is off
volumes:
  pg_data_v2:
